# Generated by Django 3.0.6 on 2020-06-08 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_warehouse_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='warehouse',
        ),
    ]
