# Generated by Django 3.0.6 on 2020-06-09 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_delete_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseitem',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Warehouse'),
            preserve_default=False,
        ),
    ]
