# Generated by Django 3.0.6 on 2020-06-15 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
