# Generated by Django 3.0.6 on 2020-06-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200615_1502'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
