# Generated by Django 3.0.6 on 2020-06-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='channel',
            field=models.CharField(blank=True, default='card', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, default='success', max_length=10, null=True),
        ),
    ]
