# Generated by Django 3.0.6 on 2020-06-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='warehouseitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('Pc(s)', 'Pc(s)'), ('Doz', 'Doz'), ('Pack(s)', 'Pack(s)'), ('Carton(s)', 'Carton(s)')], default='Pack(s)', max_length=12, null=True),
        ),
    ]
