# Generated by Django 3.0.6 on 2020-06-25 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20200625_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseitem',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Item'),
            preserve_default=False,
        ),
    ]
