# Generated by Django 3.0.6 on 2020-06-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20200629_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_shipped',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_option',
        ),
        migrations.AddField(
            model_name='order',
            name='is_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_cheque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_credit',
            field=models.BooleanField(default=False),
        ),
    ]
