# Generated by Django 3.0.6 on 2020-06-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20200629_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_card',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_cash',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_cheque',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_credit',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online Payment', 'Online Payment')], max_length=50, null=True),
        ),
    ]
