# Generated by Django 3.0.6 on 2020-07-09 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authenticate', '0005_auto_20200709_1858'),
        ('product', '0025_auto_20200630_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticate.SalesDept'),
        ),
        migrations.CreateModel(
            name='Receiveable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Paid in Full', 'Paid in Full'), ('Cheque to be cleared', 'Cheque to be cleared'), ('Not Paid', 'Not Paid')], max_length=25, null=True)),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Order')),
            ],
        ),
    ]
