# Generated by Django 3.0.6 on 2020-07-11 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_auto_20200709_1858'),
        ('product', '0026_auto_20200709_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiveable',
            name='collected_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.SalesDept'),
        ),
        migrations.AlterField(
            model_name='receiveable',
            name='status',
            field=models.CharField(blank=True, choices=[('Paid in Full', 'Paid in Full'), ('Cheque to be cleared', 'Cheque to be cleared'), ('Credit', 'Credit')], max_length=25, null=True),
        ),
    ]
