# Generated by Django 3.0.6 on 2020-07-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_auto_20200713_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_received',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online Payment', 'Online Payment'), ('Credit', 'Credit')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Receiveable',
        ),
    ]
