# Generated by Django 3.0.6 on 2020-07-16 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_auto_20200709_1858'),
        ('product', '0030_auto_20200714_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.DistributorDept'),
        ),
    ]
