# Generated by Django 3.0.6 on 2020-05-19 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=120)),
                ('other_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('company_name', models.CharField(blank=True, max_length=120, null=True)),
                ('company_reg', models.IntegerField(blank=True, null=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sales', models.BooleanField(default=False)),
                ('is_accounts', models.BooleanField(default=False)),
                ('is_general', models.BooleanField(default=False)),
                ('is_distributor', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('state', models.CharField(blank=True, max_length=15, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('image', models.ImageField(upload_to='')),
                ('telephone', models.IntegerField(blank=True, null=True)),
                ('job_role', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('other_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
