# Generated by Django 3.0.6 on 2020-05-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_warehouse',
            field=models.BooleanField(default=False),
        ),
    ]
