# Generated by Django 3.0.6 on 2020-07-09 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_auto_20200702_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributordept',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticate.SalesDept'),
        ),
        migrations.AddField(
            model_name='distributordept',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
